
version: '3.1'

services:

  server:
    image: rodezee/${PROJECT_NAME}:${VERSION}
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./www:/www
      - /var/run/docker.sock:/var/run/docker.sock
